### ISSUE TITLE
Swarm manage leaks file descriptors leading to "too many files open"

### ISSUE THREAD

**Issue by wrotki** [docker/swarm#1267]
Try running swarm manage container for a while and then doing:

sudo lsof -p <swarm process PID>

It shows a lot of socket type fds - In my case, I start and stop a lot of containers relatively quickly (several a minute), which might lead to multiple "container not found" situations when refreshing engines - and this "not found" is the condition triggering the leak.

Caused by a bug in samalba/dockerclient which swarm uses - I proposed a fix for it in the PR: https://github.com/samalba/dockerclient/pull/172

**Comment by coryb** [comment]
Just to chime in here, I ran into the same issue with my swarm manager.  Established TCP connection grows linearly with time, it seems to have no correlation to docker client activity.  

I have a graph of established connections over a week [here].(https://drive.google.com/file/d/0Bw7wjULOuWzVME1FLW5yOF90SGc/view?usp=sharing)

The graph is too linear to be related to docker client activity, leaking ~5k connections per day.  Perhaps it is related to some periodic health-check activity? The swarm nodes show a an identical linear graph, but the number of connections is divided by the number of nodes you have.   So when 30k connections were seen on my manager I had 15k established connections each on my 2 nodes.

This is effectively killing my swarm manager every week with 2 nodes, which is how long it takes to use up my 32k open file ulimit.

-Cory

**Comment by coryb** [comment]
Looking into the code, it seems pretty clear that your patch will fix this.  In my case RefreshVolumes is called every 30s which makes a call to my docker daemon which does not support the /<version>/volumes api, which returns a 404 and then leaks a connection as your patch indicates.  Hopefully this can get fixed soon.

**Comment by riuvshin** [comment]
related issue https://github.com/docker/swarm/issues/1241

**Comment by riuvshin** [comment]
ok so here is my 5 cents.
swarm version 1.0.0-rc1
docker version 1.6.0
CentOS 7.1

```
lsof | grep swarm | wc
```
gives ```7189   77996  734580```

there in lsof output were ~7k messages with (CLOSE_WAIT) state


ulimit -a

```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31503
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 16384
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 31503
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

in swarm logs:

```
time="2015-10-20T12:00:34Z" level=info msg="Registered Engine node1 at node1:2375"
time="2015-10-20T12:00:34Z" level=info msg="Registered Engine node2 at node2:2375"
2015/10/22 13:48:06 http: Accept error: accept tcp [::]:2375: accept4: too many open files; retrying in 5ms
2015/10/22 13:48:06 http: Accept error: accept tcp [::]:2375: accept4: too many open files; retrying in 10ms
2015/10/22 13:48:06 http: Accept error: accept tcp [::]:2375: accept4: too many open files; retrying in 20ms
2015/10/22 13:48:06 http: Accept error: accept tcp [::]:2375: accept4: too many open files; retrying in 40ms
2015/10/22 13:48:06 http: Accept error: accept tcp [::]:2375: accept4: too many open files; retrying in 80ms
2015/10/22 13:48:06 http: Accept error: accept tcp [::]:2375: accept4: too many open files; retrying in 160ms
2015/10/22 13:48:06 http: Accept error: accept tcp [::]:2375: accept4: too many open files; retrying in 320ms
2015/10/22 13:48:07 http: Accept error: accept tcp [::]:2375: accept4: too many open files; retrying in 640ms
```

limits were riched in ~2 days.

**Comment by aluzzardi** [comment]
Hey, thanks for the report and the fix, @wrotki!

I thought it was the end of leaking fds, we fixed a similar problem months ago :/

Perhaps we should add an integration test that checks against leaking file descriptors so it will never happen again. /cc @docker/swarm-maintainers 

@abronan Was this https://github.com/samalba/dockerclient/pull/172 ever godep updated into swarm?

@riuvshin @coryb If so, you can go ahead and use the `1.0.0-rc2` version to try out. That would be `docker run swarm:1.0.0-rc2`.

**Comment by riuvshin** [comment]
@aluzzardi Hi, it seems that issue still actual but maybe due to some other bug. I've updated swarm to latest from master with fix in dockerclient but after 2 days of work with 2 nodes it reproduced again:

```
time="2015-10-28T09:52:33Z" level=info msg="Registered Engine node1 at node1:2375"
time="2015-10-28T09:52:33Z" level=info msg="Registered Engine node2 at node2:2375"
2015/10/29 02:47:31 http: Accept error: accept tcp [::]:2375: too many open files; retrying in 1s
2015/10/29 02:47:32 http: Accept error: accept tcp [::]:2375: too many open files; retrying in 1s
time="2015-10-29T02:47:33Z" level=error msg="Discovery error: failed to read '/usr/local/swarm/node_list': open /usr/local/swarm/node_list: too many open files"
```
there is 16k nofile limit (default 1k)

Maybe it's related somehow to discovery by file?

**Comment by aluzzardi** [comment]
@riuvshin Perhaps it's simply because we didn't update to the latest dockerclient.

Will check

**Comment by riuvshin** [comment]
There is:
```
{
    "ImportPath": "github.com/samalba/dockerclient",
    "Rev": "c17bc9a62a1e2f966c05987313e187568e2ca894"
}
```
which should include fix.

**Comment by jimmyxian** [comment]
@aluzzardi Already updated.

**Comment by abronan** [comment]
@aluzzardi Yes it was already updated in dockerclient so the leak might come from somewhere else.

**Comment by aluzzardi** [comment]
@riuvshin @coryb @wrotki Can anyone of you provide a reproducible case?

I've been trying to get leaks by forcing the refresh every 1s and getting a bunch of 404s but no luck so far.

**Comment by wrotki** [comment]
My case involved stopping/deleting/creating/starting a container relatively frequently (every minute or so), no TLS. It was triggering 404s (container not found) on refresh I believe and handles left behind. But it was on 0.4.0 - with the fix I couldn't see the leak anymore. Perhaps the rate is way lower now. I didn't try 1.0.0_rc2 yet.

**Comment by abronan** [comment]
This might be related to the file discovery as mentioned by @riuvshin . Since the fix I had multiple swarm running for more than 2 days using kv discovery and couldn't replicate this behavior. Might be worth investigating there.

**Comment by coryb** [comment]
@aluzzardi I just built and pushed out the latest changes to my cluster.  It has been running for ~6 hours now and there are no leaked connections.  fwiw, I previously forked and "fixed" swarm with this gross [hack](https://github.com/coryb/swarm/commit/9f1ad2f59b34218fb661fc6a156f78e5e88d0b98)

For me the ListVolumes call was getting 404 from docker daemons and leaking the file descriptor.  My hacked swarm had been running for 3 weeks without any leaks with the commented out ListVolumes calls.

**Comment by aluzzardi** [comment]
@coryb @wrotki  Yeah I've been trying to hammer my local swarm with a bunch of requests, including 404s (docker start does_not_exist) and I haven't really noticed a leak.

Could you please keep an eye on that? It's really a critical issue.

We'll have integration tests verify we don't leak any FDs.

**Comment by wrotki** [comment]
I'm running 1.0.0-rc2 on a persistent install now, haven't noticed leakage yet  but will observe for a couple of days.

**Comment by riuvshin** [comment]
I've updated to rc3, will see if it will appear.

**Comment by abronan** [comment]
@riuvshin final `1.0.0` is available now, so you can also pull `swarm:v1.0.0` :)

**Comment by riuvshin** [comment]
So I've updated swarm to **1.0.0 (087e245)** and there is the same issue with too many open files.
I have 2 docker engines on node0 and node1 which connected to swarm.host

```
time="2015-11-10T09:36:56Z" level=info msg="Listening for HTTP" addr="0.0.0.0:23750" proto=tcp
time="2015-11-10T09:36:56Z" level=info msg="Registered Engine node0 at node0:2375"
time="2015-11-10T09:36:56Z" level=info msg="Registered Engine node1 at node1:2375"
2015/11/11 02:29:26 http: Accept error: accept tcp [::]:23750: accept4: too many open files; retrying in 5ms
2015/11/11 02:29:26 http: Accept error: accept tcp [::]:23750: accept4: too many open files; retrying in 10ms
2015/11/11 02:29:26 http: Accept error: accept tcp [::]:23750: accept4: too many open files; retrying in 20ms
2015/11/11 02:29:26 http: Accept error: accept tcp [::]:23750: accept4: too many open files; retrying in 40ms
time="2015-11-11T02:29:36Z" level=error msg="Discovery error: failed to read '/usr/local/swarm/node_list': open /usr/local/swarm/node_list: too many open files"
```

**lsof | grep swarm** gives 7k records like:

```
swarm     22492           root   10u     IPv6           72830472       0t0        TCP swarm.host:23750->swarm.host:53961 (CLOSE_WAIT)
swarm     22492           root   11u     IPv6           72830710       0t0        TCP swarm.host:23750->swarm.host:53963 (CLOSE_WAIT)
swarm     22492           root   12u     IPv6           72829625       0t0        TCP swarm.host:23750->swarm.host:53965 (CLOSE_WAIT)
swarm     22492           root   13u     IPv6           72829671       0t0        TCP swarm.host:23750->swarm.host:53966 (CLOSE_WAIT)
swarm     22492           root   14u     IPv6           72829713       0t0        TCP swarm.host:23750->swarm.host:53968 (CLOSE_WAIT)
swarm     22492           root   15u     IPv6           72829756       0t0        TCP swarm.host:23750->swarm.host:53969 (CLOSE_WAIT)
swarm     22492           root   16u     IPv6           72829805       0t0        TCP swarm.host:23750->swarm.host:53971 (CLOSE_WAIT)
swarm     22492           root   17u     IPv6           72832512       0t0        TCP swarm.host:23750->swarm.host:54030 (CLOSE_WAIT)
swarm     22492           root   18u     IPv6           72832561       0t0        TCP swarm.host:23750->swarm.host:54032 (CLOSE_WAIT)
swarm     22492           root   19u     IPv6           72832607       0t0        TCP swarm.host:23750->swarm.host:54033 (CLOSE_WAIT)
```
more info about env:
- I'm running swarm on CentOS host (not as a docker container)
- swarm discovery configured  by file
- swarm launched on custom port 23750

`nohup /usr/local/swarm/bin/swarm manage -H 0.0.0.0:23750 file:///usr/local/swarm/node_list 2>> /var/log/swarm.log & echo $! > $PID_FILE`

**Comment by abronan** [comment]
This might be a specific issue with the file discovery apparently, as I can't reproduce with `kv` discovery with a cluster running for 2 weeks now. I'll try to run my cluster with the file discovery and see. Thanks for the follow-up @riuvshin.

**Comment by coryb** [comment]
fwiw I have been running the latest release with zookeeper discovery without any issues.
-Cory

**Comment by dongluochen** [comment]
@riuvshin In your setup port 23750 is swarm service port where it receives requests. It looks like you issue the requests from the same machine (swarm.host). These connections should be closed when requests are completed. What requests do you issue? What are the state of these requests? Do you see the same problem if these requests are sent from another machine? 
```
swarm     22492           root   18u     IPv6           72832561       0t0        TCP swarm.host:23750->swarm.host:54032 (CLOSE_WAIT)
swarm     22492           root   19u     IPv6           72832607       0t0        TCP swarm.host:23750->swarm.host:54033 (CLOSE_WAIT)
```

**Comment by riuvshin** [comment]
@dongluochen Interesting. In fact I'm using sever which calls swarm API so maybe it's a problem of that server. I'll investigate this. Thank you.

**Comment by riuvshin** [comment]
Hi, some updates here. our client using **swarm evens** and it seems that there is also some leaks. it's possible to reproduce this way:
- launch swarm container ```docker run -d -p 23750:2375 swarm manage token://<TOKEN> ```
- execute few times ```docker -H tcp://localhost:23750 events```
- list openen files by ```sudo lsof | grep swarm```

on my side (ubuntu) the output is following:

```
swarm     16681                root  cwd       DIR               0,31      4096          2 /
swarm     16681                root  rtd       DIR               0,31      4096          2 /
swarm     16681                root  txt       REG               0,31  15328394         19 /swarm
swarm     16681                root    0r      CHR                1,3       0t0    1319156 /dev/null
swarm     16681                root    1w     FIFO                0,8       0t0    1319130 pipe
swarm     16681                root    2w     FIFO                0,8       0t0    1319131 pipe
swarm     16681                root    3u     sock                0,7       0t0    1320875 can't identify protocol
swarm     16681                root    4r      CHR                1,9       0t0    1319160 /dev/urandom
swarm     16681                root    5u     0000                0,9         0       7345 anon_inode
swarm     16681                root    6u     sock                0,7       0t0    1315390 can't identify protocol
swarm     16681                root    7u     sock                0,7       0t0    1361116 can't identify protocol
swarm     16681                root    8u     sock                0,7       0t0    1366482 can't identify protocol
swarm     16681                root    9u     sock                0,7       0t0    1343932 can't identify protocol
swarm     16681                root   10u     sock                0,7       0t0    1344910 can't identify protocol
swarm     16681                root   11u     sock                0,7       0t0    1369819 can't identify protocol
swarm     16681                root   12u     sock                0,7       0t0    1364521 can't identify protocol
swarm     16681                root   13u     sock                0,7       0t0    1369828 can't identify protocol
swarm     16681                root   14u     sock                0,7       0t0    1364523 can't identify protocol
swarm     16681                root   15u     sock                0,7       0t0    1367927 can't identify protocol
swarm     16681                root   16u     sock                0,7       0t0    1367929 can't identify protocol
swarm     16681                root   17u     sock                0,7       0t0    1369839 can't identify protocol
swarm     16681                root   18u     sock                0,7       0t0    1367931 can't identify protocol
swarm     16681                root   19u     sock                0,7       0t0    1406973 can't identify protocol
swarm     16681                root   20u     sock                0,7       0t0    1413176 can't identify protocol
swarm     16681                root   21u     sock                0,7       0t0    1410642 can't identify protocol
swarm     16681                root   22u     sock                0,7       0t0    1413214 can't identify protocol
swarm     16681                root   23u     sock                0,7       0t0    1410648 can't identify protocol
swarm     16681                root   24u     sock                0,7       0t0    1411144 can't identify protocol
swarm     16681                root   25u     sock                0,7       0t0    1408641 can't identify protocol
swarm     16681                root   26u     sock                0,7       0t0    1411152 can't identify protocol
swarm     16681                root   27u     sock                0,7       0t0    1410660 can't identify protocol
swarm     16681                root   28u     sock                0,7       0t0    1411156 can't identify protocol
swarm     16681                root   29u     sock                0,7       0t0    1413414 can't identify protocol
swarm     16681                root   30u     sock                0,7       0t0    1411160 can't identify protocol
swarm     16681                root   31u     sock                0,7       0t0    1414226 can't identify protocol
swarm     16681                root   32u     sock                0,7       0t0    1411164 can't identify protocol
swarm     16681                root   33u     sock                0,7       0t0    1411170 can't identify protocol
swarm     16681                root   34u     sock                0,7       0t0    1410750 can't identify protocol
swarm     16681                root   35u     sock                0,7       0t0    1411208 can't identify protocol
swarm     16681                root   36u     sock                0,7       0t0    1410754 can't identify protocol
swarm     16681                root   37u     sock                0,7       0t0    1410757 can't identify protocol
```
Each time I execute **events** list of opened files growing.

**Comment by dongluochen** [comment]
@riuvshin I think it's a minor bug that swarm doesn't close the connection when client stops the `/events` request. Swarm side would have the TCP connection at `CLOSE_WAIT` state. After each `events` request one more connection gets into such state.

**Comment by riuvshin** [comment]
Thank you for your response @dongluochen !
Yeah it's not a reason why I have too many open files, It's just something I've found. there is also something that gives leaks.
What I've found also is that we have some kind of *tcpConnectionTimeouts* (60 sec) and each 60 sec it opens 6 new connections in CLOSE_WAIT state.

We are still digging on our side, but maybe it will be somehow helpful for you.

**Comment by garagatyi** [comment]
Also looks like there is leak of file descriptors on build if client is been disconnected due to connection timeout. Maybe it is not only build API, but I haven't checked.

**Comment by abronan** [comment]
Thanks for identifying one of the culprit @riuvshin! Your feedback was super helpful! Can you give #1447 a try and confirm this fixes the issue? I can confirm it works well after reproducing the steps you described with the fix.

**Comment by riuvshin** [comment]
@abronan  Thank you! I will this fix ASAP.

**Comment by riuvshin** [comment]
Thank you guys! @abronan @dongluochen there is no more leaks due to timeouts on evens! Looking forward for a new release including this fix!
Btw as @garagatyi mentioned there could be also leaks on timeouts while executing some other commands like build. But this not so critical as it was with events.

**Comment by riuvshin** [comment]
steps to repro leaks with build:
```
curl --max-time 30 -X POST http://localhost:2375/build?remote=https://gist.githubusercontent.com/garagatyi/ea536000209b7baaa2b8/raw/1b3bd9a080bd1c27229af487b90b15d70c7ff644/gistfile1.txt
```

dockerfile:
```
FROM ubuntu

RUN sleep 365d

CMD ["echo", "hello"]
```
each time I run this curl new 6 CLOSE_WAITs appears. I think it is not only with a **build** operation

**Comment by aluzzardi** [comment]
@dongluochen @abronan Any idea if we can automate the leaks detection in our test integration suite?

**Comment by dongluochen** [comment]
@riuvshin Your case of `build` is different from `events`. In swarm `build` is scheduled to run on a selected node. When you interrupts the `build` command on the client, it just closes TCP connection from your side so you don't see the build result. The build operation continues to run on the selected node. When build operation finishes on the selected node, result will get back to swarm manager and it'll push the result and close the connection. If you change `sleep 365d` to `sleep 60s` you will see the CLOSE_WAIT connection gone after 60 seconds. For this reason I wouldn't categorize the `build` case as TCP connection leak, but a workflow issue on swarm `build` command. 
 
If user sends a break before `build` finishes, I think swarm should cancel the build process. But client could be closed for other reasons, like node failure, in such case build should continue. Unfortunately swarm manager wouldn't be able to differentiate them.

**Comment by riuvshin** [comment]
@dongluochen Confirmed, thank you! We've tested with **sleep 2m** and after 2min connections were closed.

Btw fix with events work like a charm, almost 1week without any problems. So it seems you can close issue :)

**Comment by abronan** [comment]
Thank you again @riuvshin and @wrotki and everyone involved in the discussion.

Let's close this one as I think we tackled most of what has been reported (original issue that was fixed already and the one with the swarm `events` endpoint). Feel free to open a separate issue if you see such case happening again. We'll release a `1.0.1` this week to include this fix amongst others.

**Comment by riuvshin** [comment]
@abronan Thank you!
