### ISSUE TITLE
Docker swarm manager doesn't restore exposed ports when rescheduling the container

### ISSUE THREAD

**Issue by antimack** [docker/swarm#1846]
Hi,

I have a 3 node swarm cluster with swarm token(1 manager and 2 agent nodes, daemon on all of these nodes started with params DOCKER_OPTS="-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --label=environment=test")
what has been done:
1. Swarm manager running on master node with cmd "docker run -d --name swarm_master -p 3375:2375 swarm -experimental manage token://$SW_TOKEN"
2. Swarm agents running on master node with "docker run -d --name $NODE_NAME swarm -experimental join --addr=172.18.0.12:2375 token://$SW_TOKEN"
3. I've exported DOCKER_HOST on master node and started simple Nginx container with "docker run -d --name web1 --restart=always --env="reschedule:on-node-failure" -p 80:80 nginx"

```
vagrant@master:~$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: swarm/1.1.2
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 node2: 172.18.0.12:2375
  └ Status: Healthy
  └ Containers: 0
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.019 GiB
  └ Labels: environment=test, executiondriver=native-0.2, kernelversion=3.13.0-77-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-02-19T12:43:58Z
 node3: 172.18.0.13:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.019 GiB
  └ Labels: environment=test, executiondriver=native-0.2, kernelversion=3.13.0-77-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-02-19T12:43:45Z
Plugins:
 Volume:
 Network:
Kernel Version: 3.13.0-77-generic
Operating System: linux
Architecture: amd64
CPUs: 2
Total Memory: 2.038 GiB
Name: 0e03c10fa9b4
Experimental: true
```

```
vagrant@master:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED                  STATUS                  PORTS                             NAMES
ffcc9ba41337        nginx               "nginx -g 'daemon off"   Less than a second ago   Up Less than a second   172.18.0.12:80->80/tcp, 443/tcp   node2/web1
```

I've halted node2 and wait until swarm reschedules the container on node3, I expected swarm manager reschedules nginx container with similar exposed ports, but had this instead:
```
vagrant@master:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
51ee322233b9        nginx               "nginx -g 'daemon off"   6 seconds ago       Up 6 seconds        80/tcp, 443/tcp     node3/web1
```

**Comment by nishanttotla** [comment]
@antimack is this new, or did this break recently?

**Comment by antimack** [comment]
@nishanttotla I've got this issue 2 weeks ago with 1.1.0, and I've decided to return to this and check with 1.1.2 because I thought it can be fixed in this version, but still got this issue

**Comment by vieux** [comment]
@antimack thanks for the report, it should be fixed in https://github.com/docker/swarm/pull/1850 I added a test to check.

**Comment by antimack** [comment]
Tried this in a new 1.1.3-rc1 and issue is still presented, actually re-scheduling is broken. Swarm manager re-created container with correct host-config on the healthy node but didn't start it at all.
```
vagrant@master:~$ docker -H :3375 info
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 4
Server Version: swarm/1.1.3
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 node2: 172.18.0.12:2375
  └ Status: Unhealthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.019 GiB
  └ Labels: environment=test, executiondriver=native-0.2, kernelversion=3.13.0-77-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: Cannot connect to the docker engine endpoint
  └ UpdatedAt: 2016-02-25T21:15:42Z
 node3: 172.18.0.13:2375
  └ Status: Healthy
  └ Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.019 GiB
  └ Labels: environment=test, executiondriver=native-0.2, kernelversion=3.13.0-77-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-02-25T21:17:22Z
Plugins:
 Volume:
 Network:
Kernel Version: 3.13.0-77-generic
Operating System: linux
Architecture: amd64
CPUs: 2
Total Memory: 2.038 GiB
Name: 40752132f474
Experimental: true
```

```
time="2016-02-25T21:15:42Z" level=error msg="Flagging engine as unhealthy. Connect failed 3 times" id="DRLV:32US:GUUE:RQE6:H6WP:ONAV:4XW2:OXR5:QTN6:G7BZ:SMSC:I2MJ" name=node2
time="2016-02-25T21:15:42Z" level=error msg="Error monitoring events: Get http://172.18.0.12:2375/v1.15/events: dial tcp 172.18.0.12:2375: getsockopt: connection refused" id="DRLV:32US:GUUE:RQE6:H6WP:ONAV:4XW2:OXR5:QTN6:G7BZ:SMSC:I2MJ" name=node2
time="2016-02-25T21:15:42Z" level=info msg="Rescheduled container db2a2e0085885a06e41c32cb4ba47372650425b57b9e845013e1a016ad529e6f from node2 to node3 as 52a6c1d2f41eb025088a3c628d21b85f53f64031ccc52b5962aa8be64e673d19"
time="2016-02-25T21:16:20Z" level=error msg="Update engine specs failed: Get http://172.18.0.12:2375/v1.15/info: dial tcp 172.18.0.12:2375: getsockopt: no route to host. Are you trying to connect to a TLS-enabled daemon without TLS?" id="DRLV:32US:GUUE:RQE6:H6WP:ONAV:4XW2:OXR5:QTN6:G7BZ:SMSC:I2MJ" name=node2
time="2016-02-25T21:18:54Z" level=info msg="Removed Engine node2"
```

```
vagrant@node3:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
e74e963c5d71        swarm:1.1.3-rc1     "/swarm -experimental"   9 minutes ago       Up 9 minutes        2375/tcp            swarm_node3
```

```
vagrant@node3:~$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
52a6c1d2f41e        nginx               "nginx -g 'daemon off"   4 minutes ago       Created                                 web1
e74e963c5d71        swarm:1.1.3-rc1     "/swarm -experimental"   10 minutes ago      Up 10 minutes       2375/tcp            swarm_node3
```

```
vagrant@node3:~$ docker inspect 52a6c1d2f41e
[
    {
        "Id": "52a6c1d2f41eb025088a3c628d21b85f53f64031ccc52b5962aa8be64e673d19",
        "Created": "2016-02-25T21:15:42.75620874Z",
        "Path": "nginx",
        "Args": [
            "-g",
            "daemon off;"
        ],
        "State": {
            "Status": "created",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "0001-01-01T00:00:00Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:574907042fd739107fbf6bb3ada409b1eabc05bd7f1307434006eae2ad4639e8",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "",
        "Name": "/web1",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "443/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "443"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "80"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "ShmSize": 67108864,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "KernelMemory": 0,
            "Memory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [],
        "Config": {
            "Hostname": "db2a2e008588",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "443/tcp": {},
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NGINX_VERSION=1.9.11-1~jessie"
            ],
            "Cmd": [
                "nginx",
                "-g",
                "daemon off;"
            ],
            "Image": "nginx",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.swarm.id": "3d7162f699f7d3c241ad22086c883276faa4978e9f2a2a29c0401f72381c338a",
                "com.docker.swarm.reschedule-policies": "[\"on-node-failure\"]"
            },
            "StopSignal": "SIGTERM"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": null,
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
    }
]
```

**Comment by wallnerryan** [comment]
Seeing same behavior as @antimack , container created but not started on 1.1.3 as well

**Comment by aliouba** [comment]
@vieux ,I have the same problem.
I'm using  swarm/1.2.3, docker/1.11.2 and  docker-compose/1.7.1.

![3](https://cloud.githubusercontent.com/assets/3230268/16299182/40a99a76-3939-11e6-984e-deefcc980713.png)
