### ISSUE TITLE
"docker run --rm" results in error removing container from swarm

### ISSUE THREAD

**Issue by bmitch3020** [docker/swarm#2620]
When running temporary containers through a swarm manager that is configured with a `file:///cluster.txt` list of two nodes, we are seeing the following error when the command exits:

```
$ docker run -it --rm busybox echo hello
hello
ERRO[0000] error removing container: Error response from daemon: Error response from daemon: No such container: d54fc4bbb8f25379b3d82776635df26d4bbeb155e068831e4b64207f7e23d058
```

This error is also visible in the swarm logs:

```
$ docker logs swarm-manager | tail -1
time="2017-01-31T01:55:22Z" level=error msg="HTTP error: Error response from daemon: No such container: d54fc4bbb8f25379b3d82776635df26d4bbeb155e068831e4b64207f7e23d058" status=500
```

This error is only a nuisance warning, the container has been deleted and the command returns a 0 RC. This only happens when using the `--rm` flag. Running the container and then deleting it as a separate step shows no errors:

```
$ docker run -it --name test_cleanup busybox echo hello
hello

$ docker rm test_cleanup
test_cleanup
```

We built our copy of swarm off of the master branch last week:

```
Server:
 Version:      swarm/1.2.6
 API version:  1.22 (minimum version )
 Go version:   go1.7.1
 Git commit:   c0b4734
 Built:        2017-01-24T16:08:21+0000
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by dongluochen** [comment]
This is fixed by #2617. You can test it with current master. Please reopen if you see problem.

**Comment by bmitch3020** [comment]
I tested with the most recent from master and still see the issue:

```
$ docker run -it --rm busybox echo hello
hello
ERRO[0000] error removing container: Error response from daemon: Container 4b317c7294d16845881d32cbf7d580592ca08d4c0ea0680406999cded968412f not found

$ echo $?
0

$ docker version
Client:
 Version:      1.13.0
 API version:  1.24 (downgraded from 1.25)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.2.6
 API version:  1.22 (minimum version )
 Go version:   go1.7.1
 Git commit:   76ef9d2
 Built:        2017-02-06T21:59:36+0000
 OS/Arch:      linux/amd64
 Experimental: false

$ docker logs swarm-manager
time="2017-02-06T22:06:12Z" level=info msg="Listening for HTTP" addr=":2376" proto=tcp
time="2017-02-06T22:06:12Z" level=info msg="Registered Engine **** at ****:2376"
time="2017-02-06T22:06:13Z" level=info msg="Registered Engine **** at ****:2376"
time="2017-02-06T22:06:39Z" level=error msg="HTTP error: Error response from daemon: No such container: 54e2f2151968b00d16c13a147d155318e046fe1cf735656b92e121ceccfa643a" status=500
time="2017-02-06T22:15:18Z" level=error msg="HTTP error: Error response from daemon: No such container: 87af33e835df2b3502c2e3139eb4801bf2798c5ca47f3e0232990c27dd7e2e05" status=500
time="2017-02-06T22:15:32Z" level=error msg="HTTP error: Container 4b317c7294d16845881d32cbf7d580592ca08d4c0ea0680406999cded968412f not found" status=404
```

While looking at the test code, I see that [run.bats line 34](https://github.com/docker/swarm/blob/master/test/integration/api/run.bats#L34) only checks for the exit code and not the output, so I don't believe it will catch this error.

**Comment by bmitch3020** [comment]
While digging further into this, I think the error is likely part of docker/docker itself, so I've opened [issue #30775](https://github.com/docker/docker/issues/30775) with them. Note that I'm not able to reopen this issue myself, so if you feel this is a swarm issue, I'm ok with seeing this reopened. Thanks.

**Comment by dongluochen** [comment]
You are right the issue is in Docker. Since it's resolved at Docker, we dont' need to reopen this issue.
