### ISSUE TITLE
Auth Support

### ISSUE THREAD

**Issue by ahromis** [docker/swarm#374]
I haven't been able to get swarm to work with a registry that requires authentication.  I logged in from each node, and from swarm itself but it keeps telling me image not found.  I can docker pull from each node individually and then launch them via swarm.  It also works fine with public images.

It might just not be implemented yet.  Are there plans to have auth support in the near future?  Thanks.

**Comment by vieux** [comment]
Hi @ahromis yes, we have plan to do it, currently it's unsupported because, swarm is actually pulling the images instead of letting the client pull.

This should be solved in #349

Cheers.

**Comment by csabapalfi** [comment]
Same here. I built swarm locally from the latest master. It still fails.

**Comment by vieux** [comment]
@csabapalfi you'll have to docker pull first to pull your private image on all hosts

**Comment by csabapalfi** [comment]
Yeah, I ended up with just doing docker pull locally on all swarm hosts via ansible.

**Comment by vieux** [comment]
I meant that you can do `docker pull` on swarm, it will pull on all boxes.

**Comment by theodorick** [comment]
I built swarm from master and tried pulling an image from a private registry from the manager.  It looks like it tried the pull on all 3 swarm agents instead of giving a not implemented error, but each node still says authentication required.  I verified the nodes are all logged in and I can pull the image from the private registry on the nodes.  @vieux, it looks like you implied the pull should work so I just wanted to verify.

**Comment by etuttle** [comment]
I can't pull against an a private, authenticated registry either.

It looks like swam isn't passing along the `X-Registry-Auth` header to the `/images/create` endpoint.  I think that's all that has to happen to make this work.

**Comment by vieux** [comment]
@etuttle pull will be fixed in #684

**Comment by imshashank** [comment]
Has this been fixed yet ?

On OSX I would do:
```
 boot2docker ssh
 echo 'EXTRA_ARGS="--insecure-registry <YOUR INSECURE HOST>"' | sudo tee -a /var/lib/boot2docker/profile
 sudo /etc/init.d/docker restart
```

but this doesn't get applied to the docker-machine environment.

**Comment by aluzzardi** [comment]
ping @vieux

**Comment by kevinsimper** [comment]
I am trying to pull a private image via the remote api, but I get 500, but I have no idea what went wrong, does swarm support it?

```
[{"id":"swarm-master","status":"500 Internal Server Error: EOF\n","progressDetail"}]
```

**Comment by sanga** [comment]
Any news on this? This basically means swarm is quite inconvenient to use with private images on hub.docker.com. I wound up with the same solution mentioned above: pull directly from the hub for each of the nodes in the swarm individually, but that's quite clunky.

**Comment by abronan** [comment]
@sanga This is implemented by #1384 and will be included in a `1.0.1` most probably, but this depends on another PR in `docker`.

**Comment by sanga** [comment]
excellent. Cheers!

**Comment by s093294** [comment]
Its not 100% clear if this is solved, or when it is solved - the linked PR do not seem to have related information either.

**Comment by kcraft** [comment]
Does anyone have a workaround for this other than disabling authentication on the registry?

**Comment by abronan** [comment]
@nishanttotla What is the state on this regarding `engine-api`, can this be closed?

**Comment by garagatyi** [comment]
I'm also interested in pulling from private registries on container creation. But it is not consistent with docker behaviour. Because of that systems that uses swarm transparently as it is just docker can't use that behavior. 
Also there is no output of pulling because container creation API of docker doesn't provide output. Some system might get connection read timeout since pulling can take a lot of time on systems with high load of network.

So it would be better to add such a feature to engine-api of docker. This would solve all 3 issues:
- transparent usage of Swarm as it is just docker
- auth on container creation
- streaming logs of pulling on container creaition

I do believe we discussed that quite long ago, but looks like it wasn't introduced in docker-engine. 
Maintainers, have you discussed that feature with docker-engine maintainers? Are you/they OK with such a changes in docker API? If so community will be able to work on that.

**Comment by garagatyi** [comment]
Here is suggestion of that feature by @aluzzardi  https://github.com/docker/swarm/pull/1350#issuecomment-152112163

**Comment by nishanttotla** [comment]
@garagatyi this looks like an independent discussion. Could you open a separate issue where we can discuss the best solution?

For the present issue, look at #2042 and #2272.

**Comment by garagatyi** [comment]
@nishanttotla Yes, sorry, I'll open new issue. And I checked container creation with X-Registry-Auth header and private repo on latest swarm/docker 1.11 - everything works.
So @abronan  +1 for closing that issue.
